version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app  
      POSTGRES_PASSWORD: 123456
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: franco@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 3001:80
    depends_on:
      - db
