# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 081bdce1843885e6d13490e09bcc8599049903d26252684a39f8c38c19d4d970ce5f9a9255d53c50d6d10fccfd39cf58d24432ea5fc7309bc33341ae71423ee2

test:
  secret_key_base: c6993c5487a1e7f997828ad1e2707828b750913615aeafd7e56f441083004a453342f800f72bf5e714d474a7d33c46b90d9b16992a14cb0b4995ffe3a2fc2f03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
